from __future__ import annotations

from .binance import NORMALIZATION_RULES as BINANCE_NORMALIZATION_RULES
from .bitget import NORMALIZATION_RULES as BITGET_NORMALIZATION_RULES
from .bybit import NORMALIZATION_RULES as BYBIT_NORMALIZATION_RULES
from .gateio import NORMALIZATION_RULES as GATEIO_NORMALIZATION_RULES
from .okx import NORMALIZATION_RULES as OKX_NORMALIZATION_RULES

NORMALIZATION_RULES = {
    "binance": BINANCE_NORMALIZATION_RULES,
    "bitget": BITGET_NORMALIZATION_RULES,
    "bybit": BYBIT_NORMALIZATION_RULES,
    "gateio": GATEIO_NORMALIZATION_RULES,
    "okx": OKX_NORMALIZATION_RULES,
}
